### ISSUE TITLE
佬，要不封装个docker~

### ISSUE THREAD

**Issue by cyril2007** [eeg1412/wikimoeNodeJSBlog#22]
极空间个人版不开放ssh，想用docker装一个在nas上

**Comment by eeg1412** [comment]
> 极空间个人版不开放ssh，想用docker装一个在nas上

目前有点困难

**Comment by ttimochan** [comment]
> 极空间个人版不开放ssh，想用docker装一个在nas上

我可以看看，封装一个 Docker @eeg1412

**Comment by eeg1412** [comment]
> > 极空间个人版不开放ssh，想用docker装一个在nas上
> 
> 我可以看看，封装一个 Docker @eeg1412

好咧！多谢大佬！

**Comment by ttimochan** [comment]
> 好咧！多谢大佬！

https://github.com/eeg1412/wikimoeNodeJSBlog/pull/24

文档稍后写 ~~（歇会~~

**Comment by eeg1412** [comment]
> > 好咧！多谢大佬！
> 
> #24
> 
> 文档稍后写 ~（歇会~

辛苦大佬了！

**Comment by ttimochan** [comment]
> 辛苦大佬了！

简单写了一下文档，你审核一下 PR ？

**Comment by eeg1412** [comment]
> > 辛苦大佬了！
> 
> 简单写了一下文档，你审核一下 PR ？

审核了，辛苦大佬了！谢谢

**Comment by ttimochan** [comment]
> 审核了，辛苦大佬了！谢谢
docker.yml，docker-compose.yml 等文件中的 "timochan" 得换成你自己的（

**Comment by eeg1412** [comment]
> > 辛苦大佬了！
> 
> 简单写了一下文档，你审核一下 PR ？

@ttimochan 大佬这个封装方法是将编译好的blog上传到了docker hub吗？使用docker-compose的话，其实就无法针对环境变量对blog进行再编译吗？

**Comment by ttimochan** [comment]
> > > 辛苦大佬了！
> > 
> > 
> > 简单写了一下文档，你审核一下 PR ？
> 
> @ttimochan 大佬这个封装方法是将编译好的blog上传到了docker hub吗？使用docker-compose的话，其实就无法针对环境变量对blog进行再编译吗？

可以改的，但是这样得 clone 源码，然后注入环境变量进行编译

**Comment by ttimochan** [comment]
或者就是，后端直接 Docker 部署，前端可以选择 Docker 也可以自己部署在宿主机上？如果需要变更构建的话，两者都需要拉源码

**Comment by eeg1412** [comment]
> 或者就是，后端直接 Docker 部署，前端可以选择 Docker 或者自己部署在宿主机上？如果需要变更构建的话，两者都需要拉源码

果然还是只能这样吗？就是因为这一点所以觉得现阶段还不是很适合做docker，之前想过要不要每次启动blog端的时候都进行编译，但感觉也怪怪的。

**Comment by ttimochan** [comment]
> > 或者就是，后端直接 Docker 部署，前端可以选择 Docker 或者自己部署在宿主机上？如果需要变更构建的话，两者都需要拉源码
> 
> 果然还是只能这样吗？就是因为这一点所以觉得现阶段还不是很适合做docker，之前想过要不要每次启动blog端的时候都进行编译，但感觉也怪怪的。

啊？不是呀，是资源变更需要编译，你编译好了不变更源码的话，就直接用呀

**Comment by ttimochan** [comment]
看起来可以宣布 done ？

**Comment by eeg1412** [comment]
> 看起来可以宣布 done ？

是的，多谢大佬！
@cyril2007 这边已封装docker
