### ISSUE TITLE
feature: dynamic environment variable injection for blog

### ISSUE THREAD

**Issue by ttimochan** [eeg1412/wikimoeNodeJSBlog#25]
I would like the blog program to allow for dynamic injection of environment variables after the build is completed, rather than requiring a rebuild every time an environment variable is changed.

**Comment by eeg1412** [comment]
> I would like the blog program to allow for dynamic injection of environment variables after the build is completed, rather than requiring a rebuild every time an environment variable is changed.

This is one of the main reasons I've been reluctant to use Docker; there's no way to dynamically inject environment variables.
