### ISSUE TITLE
FEAT: WebArchive Compatibility

### ISSUE THREAD

**Issue by luanyaolingwu** [eeg1412/wikimoeNodeJSBlog#30]
如果使用 [Internet Archive](https://archive.org) 来创建网页快照, 快照内容只会显示 `正在召唤神秘力量`  而不是显示为网站能正常打开时的 ~~页面~~ 社死瞬间

**Comment by eeg1412** [comment]
> 如果使用 [Internet Archive](https://archive.org) 来创建网页快照, 快照内容只会显示 `正在召唤神秘力量` 而不是显示为网站能正常打开时的 ~页面~ 社死瞬间

在配置里面有一条
`SHOW_LOADING="是否显示进入网站时的读取动画，需要时为1"`
去掉读取动画就行了
