### ISSUE TITLE
[疑问] RSS订阅链接

### ISSUE THREAD

**Issue by luanyaolingwu** [eeg1412/wikimoeNodeJSBlog#32]
![image](https://github.com/user-attachments/assets/30821c00-f586-40c1-84a2-0b72b1d6a1c4)

为啥窝的RSS订阅链接会是这样子的捏? 是我哪里设置错惹么? 
(域名又臭又长, 就不献丑惹 w)

**Comment by eeg1412** [comment]
> ![image](https://private-user-images.githubusercontent.com/105547626/354946335-30821c00-f586-40c1-84a2-0b72b1d6a1c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjUwOTYsIm5iZiI6MTcyMjgyNDc5NiwicGF0aCI6Ii8xMDU1NDc2MjYvMzU0OTQ2MzM1LTMwODIxYzAwLWY1ODYtNDBjMS04NGEyLTBiNzJiMWQ2YTFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQwMjI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2EwNzM3NmVlNzE0MmM1ODYxOWQwZTVhMDBhMmFkNjExMzU5MDg4NDYwMDU3NzczMDZiZTIwM2MyNzcxYzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H8h0iDJ6lM6MJxirO6euICcfqEbeYVWm6utHA1P_82U)
> 
> 为啥窝的RSS订阅链接会是这样子的捏? 是我哪里设置错惹么? (域名又臭又长, 就不献丑惹 w)

在管理端->设置->站点地址 中是怎么设置的？是https://blog.xxxxxxxx.com 这样的格式吗？
