### ISSUE TITLE
部署遇到的问题 & 建议

### ISSUE THREAD

**Issue by Azimiao** [eeg1412/wikimoeNodeJSBlog#8]
感谢广树开源了这套的博客系统。

基于目前的版本，我在部署后遇到了如下问题，不知道是否与我的部署环境（Windows）有关：

遇到的问题：

1. 后台界面：导航项的父导航可设置为自身，且设置后该导航项从后台界面消失（Windows 下部署）
2. 后台界面：媒体库，点击媒体按钮，在弹出的图片列表中点击图片中央，Chrome 与 Firefox 均出现较长时间的卡顿，网页停止响应或 Out of Memory（Windows 下部署）

另外还有一个建议：

1. 后台界面：文章列表页可否增加一个查看文章按钮（或简单展示文章的 url），以在未设置别名的情况下，方便拷贝文章 url（应用场景：目前导航设置中需要手动输入 url）

感谢。

**Comment by eeg1412** [comment]
> 感谢广树开源了这套的博客系统。
> 
> 基于目前的版本，我在部署后遇到了如下问题，不知道是否与我的部署环境（Windows）有关：
> 
> 遇到的问题：
> 
> 1. 后台界面：导航项的父导航可设置为自身，且设置后该导航项从后台界面消失（Windows 下部署）
> 2. 后台界面：媒体库，点击媒体按钮，在弹出的图片列表中点击图片中央，Chrome 与 Firefox 均出现较长时间的卡顿，网页停止响应或 Out of Memory（Windows 下部署）
> 
> 另外还有一个建议：
> 
> 1. 后台界面：文章列表页可否增加一个查看文章按钮（或简单展示文章的 url），以在未设置别名的情况下，方便拷贝文章 url（应用场景：目前导航设置中需要手动输入 url）
> 
> 感谢。

感谢使用博客系统，你的问题应该和windows无关。
遇到的问题：
1.确实，导航的父级选项忘记对自身去重了，这个问题将会在下个版本中修复。修复后可能需要手动操作下数据库删除无法显示的导航。
2.关于弹出图片列表中点击图片中央出现的卡顿和停止响应我这边没有出现，能否提供更加详细的信息或者截图？点击图片中央后的正常功能应该是显示这张图片的预览。我猜测可能和element ui的某些版本有内存溢出有关？请问下是不是通过yarn install安装的依赖？

建议：
1.这些建议非常实用，其实我目前有打算对这些操作做出优化。

**Comment by eeg1412** [comment]
> 感谢广树开源了这套的博客系统。
> 
> 基于目前的版本，我在部署后遇到了如下问题，不知道是否与我的部署环境（Windows）有关：
> 
> 遇到的问题：
> 
> 1. 后台界面：导航项的父导航可设置为自身，且设置后该导航项从后台界面消失（Windows 下部署）
> 2. 后台界面：媒体库，点击媒体按钮，在弹出的图片列表中点击图片中央，Chrome 与 Firefox 均出现较长时间的卡顿，网页停止响应或 Out of Memory（Windows 下部署）
> 
> 另外还有一个建议：
> 
> 1. 后台界面：文章列表页可否增加一个查看文章按钮（或简单展示文章的 url），以在未设置别名的情况下，方便拷贝文章 url（应用场景：目前导航设置中需要手动输入 url）
> 
> 感谢。

问题和建议已于0.3.1版本全部对应。
